const fs = require('fs');

const raw = `
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.activity_log\` has a foreign key \`activity_log_archived_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""activity_log"",""type"":""table"",""schema"":""public"",""fkey_name"":""activity_log_archived_by_fkey"",""fkey_columns"":[15]}",unindexed_foreign_keys_public_activity_log_activity_log_archived_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.activity_log\` has a foreign key \`activity_log_batch_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""activity_log"",""type"":""table"",""schema"":""public"",""fkey_name"":""activity_log_batch_id_fkey"",""fkey_columns"":[4]}",unindexed_foreign_keys_public_activity_log_activity_log_batch_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.api_keys\` has a foreign key \`api_keys_created_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""api_keys"",""type"":""table"",""schema"":""public"",""fkey_name"":""api_keys_created_by_fkey"",""fkey_columns"":[6]}",unindexed_foreign_keys_public_api_keys_api_keys_created_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.aql_sampling_plans\` has a foreign key \`aql_sampling_plans_created_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""aql_sampling_plans"",""type"":""table"",""schema"":""public"",""fkey_name"":""aql_sampling_plans_created_by_fkey"",""fkey_columns"":[9]}",unindexed_foreign_keys_public_aql_sampling_plans_aql_sampling_plans_created_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.aql_sampling_plans\` has a foreign key \`aql_sampling_plans_item_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""aql_sampling_plans"",""type"":""table"",""schema"":""public"",""fkey_name"":""aql_sampling_plans_item_id_fkey"",""fkey_columns"":[2]}",unindexed_foreign_keys_public_aql_sampling_plans_aql_sampling_plans_item_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.attendance_log\` has a foreign key \`attendance_log_manager_signoff_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""attendance_log"",""type"":""table"",""schema"":""public"",""fkey_name"":""attendance_log_manager_signoff_by_fkey"",""fkey_columns"":[20]}",unindexed_foreign_keys_public_attendance_log_attendance_log_manager_signoff_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_fermentation_feeds\` has a foreign key \`batch_fermentation_feeds_flask_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_fermentation_feeds"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_fermentation_feeds_flask_id_fkey"",""fkey_columns"":[9]}",unindexed_foreign_keys_public_batch_fermentation_feeds_batch_fermentation_feeds_flask_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_fermentation_reading_audit\` has a foreign key \`batch_fermentation_reading_audit_changed_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_fermentation_reading_audit"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_fermentation_reading_audit_changed_by_fkey"",""fkey_columns"":[3]}",unindexed_foreign_keys_public_batch_fermentation_reading_audit_batch_fermentation_reading_audit_changed_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_fermentation_reading_audit\` has a foreign key \`batch_fermentation_reading_audit_reading_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_fermentation_reading_audit"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_fermentation_reading_audit_reading_id_fkey"",""fkey_columns"":[2]}",unindexed_foreign_keys_public_batch_fermentation_reading_audit_batch_fermentation_reading_audit_reading_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_fermentation_readings\` has a foreign key \`batch_fermentation_readings_archived_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_fermentation_readings"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_fermentation_readings_archived_by_fkey"",""fkey_columns"":[37]}",unindexed_foreign_keys_public_batch_fermentation_readings_batch_fermentation_readings_archived_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_fermentation_readings\` has a foreign key \`batch_fermentation_readings_edited_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_fermentation_readings"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_fermentation_readings_edited_by_fkey"",""fkey_columns"":[26]}",unindexed_foreign_keys_public_batch_fermentation_readings_batch_fermentation_readings_edited_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_fermentation_readings\` has a foreign key \`batch_fermentation_readings_incubator_equipment_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_fermentation_readings"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_fermentation_readings_incubator_equipment_id_fkey"",""fkey_columns"":[24]}",unindexed_foreign_keys_public_batch_fermentation_readings_batch_fermentation_readings_incubator_equipment_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_fermentation_readings\` has a foreign key \`batch_fermentation_readings_logged_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_fermentation_readings"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_fermentation_readings_logged_by_fkey"",""fkey_columns"":[13]}",unindexed_foreign_keys_public_batch_fermentation_readings_batch_fermentation_readings_logged_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_fermentation_readings\` has a foreign key \`batch_fermentation_readings_updated_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_fermentation_readings"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_fermentation_readings_updated_by_fkey"",""fkey_columns"":[22]}",unindexed_foreign_keys_public_batch_fermentation_readings_batch_fermentation_readings_updated_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_endpoints\` has a foreign key \`batch_flask_endpoints_edited_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_endpoints"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_endpoints_edited_by_fkey"",""fkey_columns"":[18]}",unindexed_foreign_keys_public_batch_flask_endpoints_batch_flask_endpoints_edited_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_inoculations\` has a foreign key \`batch_flask_inoculations_capa_deviation_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_inoculations"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_inoculations_capa_deviation_id_fkey"",""fkey_columns"":[16]}",unindexed_foreign_keys_public_batch_flask_inoculations_batch_flask_inoculations_capa_deviation_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_qc_tests\` has a foreign key \`batch_flask_qc_tests_retest_of_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_qc_tests"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_qc_tests_retest_of_fkey"",""fkey_columns"":[10]}",unindexed_foreign_keys_public_batch_flask_qc_tests_batch_flask_qc_tests_retest_of_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_qc_tests\` has a foreign key \`batch_flask_qc_tests_tested_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_qc_tests"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_qc_tests_tested_by_fkey"",""fkey_columns"":[11]}",unindexed_foreign_keys_public_batch_flask_qc_tests_batch_flask_qc_tests_tested_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_rejection_record\` has a foreign key \`batch_flask_rejection_record_batch_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_rejection_record"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_rejection_record_batch_id_fkey"",""fkey_columns"":[13]}",unindexed_foreign_keys_public_batch_flask_rejection_record_batch_flask_rejection_record_batch_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_rejection_record\` has a foreign key \`batch_flask_rejection_record_implicated_lot_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_rejection_record"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_rejection_record_implicated_lot_id_fkey"",""fkey_columns"":[12]}",unindexed_foreign_keys_public_batch_flask_rejection_record_batch_flask_rejection_record_implicated_lot_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_release_record\` has a foreign key \`batch_flask_release_record_batch_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_release_record"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_release_record_batch_id_fkey"",""fkey_columns"":[9]}",unindexed_foreign_keys_public_batch_flask_release_record_batch_flask_release_record_batch_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_release_record\` has a foreign key \`batch_flask_release_record_formulation_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_release_record"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_release_record_formulation_id_fkey"",""fkey_columns"":[15]}",unindexed_foreign_keys_public_batch_flask_release_record_batch_flask_release_record_formulation_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_release_record\` has a foreign key \`batch_flask_release_record_label_verified_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_release_record"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_release_record_label_verified_by_fkey"",""fkey_columns"":[19]}",unindexed_foreign_keys_public_batch_flask_release_record_batch_flask_release_record_label_verified_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_straining\` has a foreign key \`batch_flask_straining_centrifuge_equipment_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_straining"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_straining_centrifuge_equipment_id_fkey"",""fkey_columns"":[21]}",unindexed_foreign_keys_public_batch_flask_straining_batch_flask_straining_centrifuge_equipment_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_straining\` has a foreign key \`batch_flask_straining_ph_meter_equipment_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_straining"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_straining_ph_meter_equipment_id_fkey"",""fkey_columns"":[22]}",unindexed_foreign_keys_public_batch_flask_straining_batch_flask_straining_ph_meter_equipment_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_flask_straining\` has a foreign key \`batch_flask_straining_scale_equipment_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_flask_straining"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_flask_straining_scale_equipment_id_fkey"",""fkey_columns"":[23]}",unindexed_foreign_keys_public_batch_flask_straining_batch_flask_straining_scale_equipment_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_stage_downstream\` has a foreign key \`batch_stage_downstream_flask_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_stage_downstream"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_stage_downstream_flask_id_fkey"",""fkey_columns"":[12]}",unindexed_foreign_keys_public_batch_stage_downstream_batch_stage_downstream_flask_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_stage_harvest\` has a foreign key \`batch_stage_harvest_flask_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_stage_harvest"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_stage_harvest_flask_id_fkey"",""fkey_columns"":[17]}",unindexed_foreign_keys_public_batch_stage_harvest_batch_stage_harvest_flask_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_stage_media_prep\` has a foreign key \`batch_stage_media_prep_ph_meter_equipment_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_stage_media_prep"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_stage_media_prep_ph_meter_equipment_id_fkey"",""fkey_columns"":[24]}",unindexed_foreign_keys_public_batch_stage_media_prep_batch_stage_media_prep_ph_meter_equipment_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_stage_media_prep\` has a foreign key \`batch_stage_media_prep_scale_equipment_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_stage_media_prep"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_stage_media_prep_scale_equipment_id_fkey"",""fkey_columns"":[23]}",unindexed_foreign_keys_public_batch_stage_media_prep_batch_stage_media_prep_scale_equipment_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batch_stage_sterilisation\` has a foreign key \`batch_stage_sterilisation_capa_deviation_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batch_stage_sterilisation"",""type"":""table"",""schema"":""public"",""fkey_name"":""batch_stage_sterilisation_capa_deviation_id_fkey"",""fkey_columns"":[20]}",unindexed_foreign_keys_public_batch_stage_sterilisation_batch_stage_sterilisation_capa_deviation_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.batches\` has a foreign key \`batches_archived_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""batches"",""type"":""table"",""schema"":""public"",""fkey_name"":""batches_archived_by_fkey"",""fkey_columns"":[27]}",unindexed_foreign_keys_public_batches_batches_archived_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.bioprocess_experiments\` has a foreign key \`bioprocess_experiments_created_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""bioprocess_experiments"",""type"":""table"",""schema"":""public"",""fkey_name"":""bioprocess_experiments_created_by_fkey"",""fkey_columns"":[8]}",unindexed_foreign_keys_public_bioprocess_experiments_bioprocess_experiments_created_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.bioprocess_experiments\` has a foreign key \`bioprocess_experiments_sop_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""bioprocess_experiments"",""type"":""table"",""schema"":""public"",""fkey_name"":""bioprocess_experiments_sop_id_fkey"",""fkey_columns"":[14]}",unindexed_foreign_keys_public_bioprocess_experiments_bioprocess_experiments_sop_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.capa_actions\` has a foreign key \`capa_actions_archived_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""capa_actions"",""type"":""table"",""schema"":""public"",""fkey_name"":""capa_actions_archived_by_fkey"",""fkey_columns"":[10]}",unindexed_foreign_keys_public_capa_actions_capa_actions_archived_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.capa_actions\` has a foreign key \`capa_actions_created_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""capa_actions"",""type"":""table"",""schema"":""public"",""fkey_name"":""capa_actions_created_by_fkey"",""fkey_columns"":[8]}",unindexed_foreign_keys_public_capa_actions_capa_actions_created_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.cell_bank_preparations\` has a foreign key \`cell_bank_preparations_created_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""cell_bank_preparations"",""type"":""table"",""schema"":""public"",""fkey_name"":""cell_bank_preparations_created_by_fkey"",""fkey_columns"":[11]}",unindexed_foreign_keys_public_cell_bank_preparations_cell_bank_preparations_created_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.cell_bank_preparations\` has a foreign key \`cell_bank_preparations_qc_released_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""cell_bank_preparations"",""type"":""table"",""schema"":""public"",""fkey_name"":""cell_bank_preparations_qc_released_by_fkey"",""fkey_columns"":[17]}",unindexed_foreign_keys_public_cell_bank_preparations_cell_bank_preparations_qc_released_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.cell_bank_preparations\` has a foreign key \`cell_bank_preparations_source_vial_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""cell_bank_preparations"",""type"":""table"",""schema"":""public"",""fkey_name"":""cell_bank_preparations_source_vial_id_fkey"",""fkey_columns"":[15]}",unindexed_foreign_keys_public_cell_bank_preparations_cell_bank_preparations_source_vial_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.cell_bank_strains\` has a foreign key \`cell_bank_strains_created_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""cell_bank_strains"",""type"":""table"",""schema"":""public"",""fkey_name"":""cell_bank_strains_created_by_fkey"",""fkey_columns"":[10]}",unindexed_foreign_keys_public_cell_bank_strains_cell_bank_strains_created_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.cell_bank_vial_logs\` has a foreign key \`cell_bank_vial_logs_batch_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""cell_bank_vial_logs"",""type"":""table"",""schema"":""public"",""fkey_name"":""cell_bank_vial_logs_batch_id_fkey"",""fkey_columns"":[4]}",unindexed_foreign_keys_public_cell_bank_vial_logs_cell_bank_vial_logs_batch_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.cell_bank_vial_logs\` has a foreign key \`cell_bank_vial_logs_flask_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""cell_bank_vial_logs"",""type"":""table"",""schema"":""public"",""fkey_name"":""cell_bank_vial_logs_flask_id_fkey"",""fkey_columns"":[5]}",unindexed_foreign_keys_public_cell_bank_vial_logs_cell_bank_vial_logs_flask_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.cell_bank_vial_logs\` has a foreign key \`cell_bank_vial_logs_operator_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""cell_bank_vial_logs"",""type"":""table"",""schema"":""public"",""fkey_name"":""cell_bank_vial_logs_operator_id_fkey"",""fkey_columns"":[6]}",unindexed_foreign_keys_public_cell_bank_vial_logs_cell_bank_vial_logs_operator_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.cell_bank_vials\` has a foreign key \`cell_bank_vials_used_in_batch_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""cell_bank_vials"",""type"":""table"",""schema"":""public"",""fkey_name"":""cell_bank_vials_used_in_batch_id_fkey"",""fkey_columns"":[10]}",unindexed_foreign_keys_public_cell_bank_vials_cell_bank_vials_used_in_batch_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.cell_bank_vials\` has a foreign key \`cell_bank_vials_used_in_study_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""cell_bank_vials"",""type"":""table"",""schema"":""public"",""fkey_name"":""cell_bank_vials_used_in_study_id_fkey"",""fkey_columns"":[14]}",unindexed_foreign_keys_public_cell_bank_vials_cell_bank_vials_used_in_study_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.chat_attachments\` has a foreign key \`chat_attachments_uploaded_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""chat_attachments"",""type"":""table"",""schema"":""public"",""fkey_name"":""chat_attachments_uploaded_by_fkey"",""fkey_columns"":[6]}",unindexed_foreign_keys_public_chat_attachments_chat_attachments_uploaded_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.chat_members\` has a foreign key \`chat_members_employee_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""chat_members"",""type"":""table"",""schema"":""public"",""fkey_name"":""chat_members_employee_id_fkey"",""fkey_columns"":[3]}",unindexed_foreign_keys_public_chat_members_chat_members_employee_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.chats\` has a foreign key \`chats_created_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""chats"",""type"":""table"",""schema"":""public"",""fkey_name"":""chats_created_by_fkey"",""fkey_columns"":[4]}",unindexed_foreign_keys_public_chats_chats_created_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.customer_complaints\` has a foreign key \`customer_complaints_logged_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""customer_complaints"",""type"":""table"",""schema"":""public"",""fkey_name"":""customer_complaints_logged_by_fkey"",""fkey_columns"":[8]}",unindexed_foreign_keys_public_customer_complaints_customer_complaints_logged_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.deviations\` has a foreign key \`deviations_archived_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""deviations"",""type"":""table"",""schema"":""public"",""fkey_name"":""deviations_archived_by_fkey"",""fkey_columns"":[22]}",unindexed_foreign_keys_public_deviations_deviations_archived_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.deviations\` has a foreign key \`deviations_created_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""deviations"",""type"":""table"",""schema"":""public"",""fkey_name"":""deviations_created_by_fkey"",""fkey_columns"":[19]}",unindexed_foreign_keys_public_deviations_deviations_created_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.deviations\` has a foreign key \`deviations_inventory_stock_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""deviations"",""type"":""table"",""schema"":""public"",""fkey_name"":""deviations_inventory_stock_id_fkey"",""fkey_columns"":[12]}",unindexed_foreign_keys_public_deviations_deviations_inventory_stock_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.deviations\` has a foreign key \`deviations_sample_incubation_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""deviations"",""type"":""table"",""schema"":""public"",""fkey_name"":""deviations_sample_incubation_id_fkey"",""fkey_columns"":[13]}",unindexed_foreign_keys_public_deviations_deviations_sample_incubation_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.emp_samples\` has a foreign key \`emp_samples_capa_deviation_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""emp_samples"",""type"":""table"",""schema"":""public"",""fkey_name"":""emp_samples_capa_deviation_id_fkey"",""fkey_columns"":[11]}",unindexed_foreign_keys_public_emp_samples_emp_samples_capa_deviation_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.emp_samples\` has a foreign key \`emp_samples_location_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""emp_samples"",""type"":""table"",""schema"":""public"",""fkey_name"":""emp_samples_location_id_fkey"",""fkey_columns"":[2]}",unindexed_foreign_keys_public_emp_samples_emp_samples_location_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.emp_samples\` has a foreign key \`emp_samples_sampled_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""emp_samples"",""type"":""table"",""schema"":""public"",""fkey_name"":""emp_samples_sampled_by_fkey"",""fkey_columns"":[3]}",unindexed_foreign_keys_public_emp_samples_emp_samples_sampled_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.employees\` has a foreign key \`employees_shift_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""employees"",""type"":""table"",""schema"":""public"",""fkey_name"":""employees_shift_id_fkey"",""fkey_columns"":[26]}",unindexed_foreign_keys_public_employees_employees_shift_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.equipment\` has a foreign key \`equipment_archived_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""equipment"",""type"":""table"",""schema"":""public"",""fkey_name"":""equipment_archived_by_fkey"",""fkey_columns"":[9]}",unindexed_foreign_keys_public_equipment_equipment_archived_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.equipment\` has a foreign key \`equipment_registered_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""equipment"",""type"":""table"",""schema"":""public"",""fkey_name"":""equipment_registered_by_fkey"",""fkey_columns"":[14]}",unindexed_foreign_keys_public_equipment_equipment_registered_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.equipment_tickets\` has a foreign key \`equipment_tickets_equipment_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""equipment_tickets"",""type"":""table"",""schema"":""public"",""fkey_name"":""equipment_tickets_equipment_id_fkey"",""fkey_columns"":[2]}",unindexed_foreign_keys_public_equipment_tickets_equipment_tickets_equipment_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.equipment_tickets\` has a foreign key \`equipment_tickets_reported_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""equipment_tickets"",""type"":""table"",""schema"":""public"",""fkey_name"":""equipment_tickets_reported_by_fkey"",""fkey_columns"":[7]}",unindexed_foreign_keys_public_equipment_tickets_equipment_tickets_reported_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.equipment_tickets\` has a foreign key \`equipment_tickets_resolved_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""equipment_tickets"",""type"":""table"",""schema"":""public"",""fkey_name"":""equipment_tickets_resolved_by_fkey"",""fkey_columns"":[8]}",unindexed_foreign_keys_public_equipment_tickets_equipment_tickets_resolved_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.formulations\` has a foreign key \`formulations_archived_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""formulations"",""type"":""table"",""schema"":""public"",""fkey_name"":""formulations_archived_by_fkey"",""fkey_columns"":[19]}",unindexed_foreign_keys_public_formulations_formulations_archived_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.growth_measurements\` has a foreign key \`growth_measurements_archived_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""growth_measurements"",""type"":""table"",""schema"":""public"",""fkey_name"":""growth_measurements_archived_by_fkey"",""fkey_columns"":[21]}",unindexed_foreign_keys_public_growth_measurements_growth_measurements_archived_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.growth_measurements\` has a foreign key \`growth_measurements_recorded_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""growth_measurements"",""type"":""table"",""schema"":""public"",""fkey_name"":""growth_measurements_recorded_by_fkey"",""fkey_columns"":[19]}",unindexed_foreign_keys_public_growth_measurements_growth_measurements_recorded_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.growth_measurements\` has a foreign key \`growth_measurements_time_point_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""growth_measurements"",""type"":""table"",""schema"":""public"",""fkey_name"":""growth_measurements_time_point_id_fkey"",""fkey_columns"":[3]}",unindexed_foreign_keys_public_growth_measurements_growth_measurements_time_point_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.growth_plate_observations\` has a foreign key \`growth_plate_observations_recorded_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""growth_plate_observations"",""type"":""table"",""schema"":""public"",""fkey_name"":""growth_plate_observations_recorded_by_fkey"",""fkey_columns"":[16]}",unindexed_foreign_keys_public_growth_plate_observations_growth_plate_observations_recorded_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.growth_plate_observations\` has a foreign key \`growth_plate_observations_time_point_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""growth_plate_observations"",""type"":""table"",""schema"":""public"",""fkey_name"":""growth_plate_observations_time_point_id_fkey"",""fkey_columns"":[3]}",unindexed_foreign_keys_public_growth_plate_observations_growth_plate_observations_time_point_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.growth_studies\` has a foreign key \`growth_studies_archived_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""growth_studies"",""type"":""table"",""schema"":""public"",""fkey_name"":""growth_studies_archived_by_fkey"",""fkey_columns"":[34]}",unindexed_foreign_keys_public_growth_studies_growth_studies_archived_by_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.growth_studies\` has a foreign key \`growth_studies_cell_bank_preparation_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""growth_studies"",""type"":""table"",""schema"":""public"",""fkey_name"":""growth_studies_cell_bank_preparation_id_fkey"",""fkey_columns"":[6]}",unindexed_foreign_keys_public_growth_studies_growth_studies_cell_bank_preparation_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.growth_studies\` has a foreign key \`growth_studies_cell_bank_strain_id_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""growth_studies"",""type"":""table"",""schema"":""public"",""fkey_name"":""growth_studies_cell_bank_strain_id_fkey"",""fkey_columns"":[5]}",unindexed_foreign_keys_public_growth_studies_growth_studies_cell_bank_strain_id_fkey
unindexed_foreign_keys,Unindexed foreign keys,INFO,EXTERNAL,"[""PERFORMANCE""]","Identifies foreign key constraints without a covering index, which can impact database performance.",Table \`public.growth_studies\` has a foreign key \`growth_studies_created_by_fkey\` without a covering index. This can lead to suboptimal query performance.,https://supabase.com/docs/guides/database/database-linter?lint=0001_unindexed_foreign_keys,"{""name"":""growth_studies"",""type"":""table"",""schema"":""public"",""fkey_name"":""growth_studies_created_by_fkey"",""fkey_columns"":[28]}",unindexed_foreign_keys_public_growth_studies_growth_studies_created_by_fkey
`;

let sql = '-- Migration to add missing foreign key indexes\n\n';

const lines = raw.trim().split('\n');
for (const line of lines) {
  const match = line.match(/"{""name"":""([^"]+)"",""type"":""table"",""schema"":""public"",""fkey_name"":""([^"]+)""/);
  if (match) {
    const table = match[1];
    const fkey = match[2];
    
    // Attempt to derive column name from fkey
    // standard is table_column_fkey
    if (fkey.startsWith(table + '_') && fkey.endsWith('_fkey')) {
      const col = fkey.substring(table.length + 1, fkey.length - 5);
      const idxName = `idx_${table}_${col}`.substring(0, 63);
      sql += `CREATE INDEX CONCURRENTLY IF NOT EXISTS ${idxName} ON public.${table} (${col});\n`;
    } else {
      // It might be like users_id_fkey on table profiles
      // Or just column_fkey
      let col = fkey.replace('_fkey', '');
      if (col.startsWith(table + '_')) {
          col = col.substring(table.length + 1);
      }
      const idxName = `idx_${table}_${col}`.substring(0, 63);
      sql += `CREATE INDEX CONCURRENTLY IF NOT EXISTS ${idxName} ON public.${table} (${col});\n`;
    }
  }
}

fs.writeFileSync('supabase/migrations/20260805000001_add_missing_fk_indexes.sql', sql);
console.log('Done!');
