import { z } from 'zod';

export const incubationSchema = z.object({
  id: z.string().uuid().optional(),
  sample_name: z.string().trim().min(1, 'Sample name is required').max(120),
  batch_id: z.string().uuid().nullable().optional(),
  flask_id: z.string().uuid().nullable().optional(),
  qc_sample_id: z.string().uuid().nullable().optional(),
  fermentation_reading_id: z.string().uuid().nullable().optional(),
  lab_bench_sample_id: z.string().uuid().nullable().optional(),
  source_id: z.string().trim().max(120).nullable().optional(),
  source_label: z.string().trim().max(160).nullable().optional(),
  log_hour: z.coerce.number().min(0).nullable().optional(),
  timepoint_label: z.string().trim().max(80).nullable().optional(),
  plate_label: z.string().trim().max(80).nullable().optional(),
  plate_index: z.coerce.number().int().min(1).nullable().optional(),
  plate_total: z.coerce.number().int().min(1).nullable().optional(),
  source_stage: z.string().trim().max(80).nullable().optional(),
  source_type: z.string().trim().max(120).nullable().optional(),
  sampled_at: z.string().datetime({ offset: true }).nullable().optional(),
  sample_category: z.enum(['Fermentation IPC', 'Cell Bank', 'Passage', 'Subculture', 'Other']),
  sample_type: z.enum(['Agar Plate', 'Broth']),
  incubation_date: z.string().min(1, 'Incubation date is required'),
  incubation_temp_c: z.coerce.number().min(0).max(100),
  start_time: z.string().datetime({ offset: true }),
  end_time: z.string().datetime({ offset: true }).nullable().optional(),
  od_value: z.coerce.number().min(0).max(10).nullable().optional(),
  ph_value: z.coerce.number().min(0).max(14).nullable().optional(),
  colony_count: z.coerce.number().int().min(0).nullable().optional(),
  cfu_per_ml: z.coerce.number().min(0).nullable().optional(),
  staining_method: z.string().trim().max(120).nullable().optional(),
  microscopic_morphology: z.string().trim().max(500).nullable().optional(),
  colony_morphology: z.string().trim().max(1000).nullable().optional(),
  sterility_status: z.enum(['Pending', 'Sterile', 'Contaminated']).default('Pending'),
  observation: z.string().trim().max(8000).nullable().optional(),
  dilution_factor: z.coerce.number().min(0).nullable().optional(),
  volume_plated_ml: z.coerce.number().min(0).nullable().optional(),
  replicate_label: z.string().trim().max(20).nullable().optional(),
  media_used: z.string().trim().max(200).nullable().optional(),
  media_lot: z.string().trim().max(200).nullable().optional(),
  media_inventory_item_id: z.string().uuid().nullable().optional(),
  media_volume_used_ml: z.coerce.number().min(0).nullable().optional(),
  formulation_id: z.string().uuid().nullable().optional(),
  manual_entry_no: z.string().trim().max(30).nullable().optional(),
  editReason: z.string().trim().min(5, 'Reason for change must be at least 5 characters').max(200).optional(),
}).refine((data) => {
  if (!data.end_time) return true;
  return new Date(data.end_time).getTime() >= new Date(data.start_time).getTime();
}, {
  message: 'End time cannot be before start time',
  path: ['end_time']
});
